---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.5.1/charts/library/common/values.schema.json

controllers:
  cors-proxy:
    enabled: true
    type: deployment
    replicas: 1
    strategy: Recreate
    revisionHistoryLimit: 1
    containers:
      cors-proxy:
        image:
          repository: ghcr.io/hiteshnayak305/cors-proxy
          tag: 1.0.0
          pullPolicy: IfNotPresent
        env:
          ORIGIN: "*"
        envFrom: []
        ports:
          - name: http
            containerPort: 3000
            protocol: TCP
        probes:
          liveness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /
                port: http
          readiness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /
                port: http
          startup:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /
                port: http
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 128Mi
#--
service:
  cors-proxy:
    enabled: true
    controller: cors-proxy
    primary: true
    type: ClusterIP
    ports:
      http:
        enabled: true
        primary: true
        port: 3000
        protocol: HTTP
