name: pull-request
on:
  workflow_dispatch:
    inputs: {}
  pull_request:
    branches: ["master", "main"]
permissions: read-all
jobs:
  build-app:
    runs-on: "ubuntu-latest"
    steps:
      - id: test
        name: test
        run: echo '[TODO] Run tests for proxy server'
  build-docker:
    needs: build-app
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          push: false
          tags: ghcr.io/hiteshnayak305/cors-proxy:pr
  build-helm:
    runs-on: "ubuntu-latest"
    steps:
      - name: Install helm
        uses: azure/setup-helm@v4.3.1

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Helm Dependency Update
        run: helm dependency update charts/cors-proxy

      - name: Helm Lint
        run: helm lint charts/cors-proxy

      - name: Helm Template
        run: helm template --debug test charts/cors-proxy
